version: '3.7'

services:

  node:
    image: "mcr.microsoft.com/devcontainers/javascript-node:0-20"
    volumes: 
      - sqlitedb:/etc/todos
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  sqlitedb:
